### ISSUE TITLE
CSS Transitions

### ISSUE THREAD

**Issue by bradley-varol** [timc1/postel#43]
Is it possible to use this library with CSS (class) transitions? I'd like to use it with TailwindCSS.

**Comment by timc1** [comment]
Hey @bradley-varol, dynamic classNames are not currently supported, though it should be quite simple to add these as additional props.

**Comment by bradley-varol** [comment]
Thanks for such a quick response! Looks like I'd need to change the `visibility` implementation to one based on `opacity` so it can be animated with CSS!
